#############################################################################
# Makefile for building: bin/serialtool
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Apr 8 09:46:24 2013
# Project:  serialtool.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile serialtool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I/usr/include/QtTest -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtTest -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/comtoolmain.cpp \
		src/serialtool.cpp build/moc_serialtool.cpp \
		build/moc_myqcombobox.cpp \
		build/moc_myqlineedit.cpp \
		qrc_myresource.cpp
OBJECTS       = build/comtoolmain.o \
		build/serialtool.o \
		build/moc_serialtool.o \
		build/moc_myqcombobox.o \
		build/moc_myqlineedit.o \
		build/qrc_myresource.o
DIST          = /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/qtestlib.prf \
		/usr/lib/qt4/mkspecs/features/staticlib.prf \
		/usr/lib/qt4/mkspecs/features/static.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		serialtool.pro
QMAKE_TARGET  = serialtool
DESTDIR       = bin/
TARGET        = bin/serialtool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_serialtool.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: serialtool.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base.conf \
		/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt4/mkspecs/common/g++-base.conf \
		/usr/lib/qt4/mkspecs/common/g++-unix.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/debug.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/qtestlib.prf \
		/usr/lib/qt4/mkspecs/features/staticlib.prf \
		/usr/lib/qt4/mkspecs/features/static.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtTest.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -o Makefile serialtool.pro
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/common/gcc-base.conf:
/usr/lib/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt4/mkspecs/common/g++-base.conf:
/usr/lib/qt4/mkspecs/common/g++-unix.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_phonon.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/debug.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/qtestlib.prf:
/usr/lib/qt4/mkspecs/features/staticlib.prf:
/usr/lib/qt4/mkspecs/features/static.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtTest.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile serialtool.pro

dist: 
	@$(CHK_DIR_EXISTS) build/serialtool1.0.0 || $(MKDIR) build/serialtool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/serialtool1.0.0/ && $(COPY_FILE) --parents src/serialtool.h build/myqcombobox.h build/myqlineedit.h build/serialtool1.0.0/ && $(COPY_FILE) --parents ui/myresource.qrc build/serialtool1.0.0/ && $(COPY_FILE) --parents src/comtoolmain.cpp src/serialtool.cpp build/serialtool1.0.0/ && $(COPY_FILE) --parents ui/serialtool.ui build/serialtool1.0.0/ && (cd `dirname build/serialtool1.0.0` && $(TAR) serialtool1.0.0.tar serialtool1.0.0 && $(COMPRESS) serialtool1.0.0.tar) && $(MOVE) `dirname build/serialtool1.0.0`/serialtool1.0.0.tar.gz . && $(DEL_FILE) -r build/serialtool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_serialtool.cpp build/moc_myqcombobox.cpp build/moc_myqlineedit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_serialtool.cpp build/moc_myqcombobox.cpp build/moc_myqlineedit.cpp
build/moc_serialtool.cpp: build/ui_serialtool.h \
		src/serialtool.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/serialtool.h -o build/moc_serialtool.cpp

build/moc_myqcombobox.cpp: build/myqcombobox.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) build/myqcombobox.h -o build/moc_myqcombobox.cpp

build/moc_myqlineedit.cpp: build/myqlineedit.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) build/myqlineedit.h -o build/moc_myqlineedit.cpp

compiler_rcc_make_all: qrc_myresource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_myresource.cpp
qrc_myresource.cpp: ui/myresource.qrc \
		ui/thank.png \
		ui/close.jpg \
		ui/erroring.png \
		ui/error.jpg \
		ui/success.png \
		ui/off.jpg \
		ui/network.jpg \
		ui/on.jpg
	/usr/lib/qt4/bin/rcc -name myresource ui/myresource.qrc -o qrc_myresource.cpp

compiler_image_collection_make_all: build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_serialtool.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_serialtool.h
build/ui_serialtool.h: ui/serialtool.ui
	/usr/lib/qt4/bin/uic ui/serialtool.ui -o build/ui_serialtool.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/comtoolmain.o: src/comtoolmain.cpp src/serialtool.h \
		build/ui_serialtool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/comtoolmain.o src/comtoolmain.cpp

build/serialtool.o: src/serialtool.cpp src/serialtool.h \
		build/ui_serialtool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/serialtool.o src/serialtool.cpp

build/moc_serialtool.o: build/moc_serialtool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_serialtool.o build/moc_serialtool.cpp

build/moc_myqcombobox.o: build/moc_myqcombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_myqcombobox.o build/moc_myqcombobox.cpp

build/moc_myqlineedit.o: build/moc_myqlineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_myqlineedit.o build/moc_myqlineedit.cpp

build/qrc_myresource.o: qrc_myresource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_myresource.o qrc_myresource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

